### PR TITLE
Added support for Qualisys mocap system

### PR DESCRIPTION
**Pull request by FlorisE**
I added support for the Qualisis motion capture system. It's tested with an 8 camera Qualisys Miqus setup.

Also added an application or visualizing markers in rviz.

Also added MarkerWithId and MarkersWithId message type to make it easier to keep track of identified markers.

Initially I also added some code for estimating the robot configuration using mocap markers, but this is still under development so I moved it to a separate branch.

### CODE REVIEW

**Comment by lbajo** [comment]
Hello Floris,
We are currently working on correcting some CI problems. As soon as we finish we will review your PR.
Thank you very much for your contribution.

PS: Is Qualisys a library that must also be installed on the system?

**Comment by FlorisE** [comment]
Hello Lorena,

I guess I should look into some CI problems with our Qualisys implementation as well. It does depend on the Qualisys SDK, both in terms of headers and as a binary. Their SDK is open source and on GitHub, so it might be possible to automatically pull and build it. I will look into it a bit more.

**Comment by FlorisE** [comment]
Right now we can build the workspace by excluding the Vicon driver (using `colcon build --packages-skip`), but this would get more and more cumbersome if more drivers are added. I support your proposal of creating a GitHub project with multiple repos.

**Comment by fmrico** [comment]
Hi @FlorisE 

Sorry for the late response. I have been out and now I have time for this. I thought that I or @lbajo had already merged this PR.

I am going to merge this, but we are moving to https://github.com/MOCAP4ROS2-Project.

I will add a repo for this driver, and I will add you as the owner. 

Is it possible to have a bag file or something similar to test this driver?

Best!!

**Pull request merged**
